!! Deallocates up to 12 optionally arrays of any number of dimensions

  IF(ALLOCATED(A0)) DEALLOCATE(A0)

  IF(PRESENT(A1)) THEN
    IF(ALLOCATED(A1)) DEALLOCATE(A1)
  ENDIF
  IF(PRESENT(A2)) THEN
    IF(ALLOCATED(A2)) DEALLOCATE(A2)
  ENDIF
  IF(PRESENT(A3)) THEN
    IF(ALLOCATED(A3)) DEALLOCATE(A3)
  ENDIF
  IF(PRESENT(A4)) THEN
    IF(ALLOCATED(A4)) DEALLOCATE(A4)
  ENDIF
  IF(PRESENT(A5)) THEN
    IF(ALLOCATED(A5)) DEALLOCATE(A5)
  ENDIF
  IF(PRESENT(A6)) THEN
    IF(ALLOCATED(A6)) DEALLOCATE(A6)
  ENDIF
  IF(PRESENT(A7)) THEN
    IF(ALLOCATED(A7)) DEALLOCATE(A7)
  ENDIF
  IF(PRESENT(A8)) THEN
    IF(ALLOCATED(A8)) DEALLOCATE(A8)
  ENDIF
  IF(PRESENT(A9)) THEN
    IF(ALLOCATED(A9)) DEALLOCATE(A9)
  ENDIF
  IF(PRESENT(A10)) THEN
    IF(ALLOCATED(A10)) DEALLOCATE(A10)
  ENDIF
  IF(PRESENT(A11)) THEN
    IF(ALLOCATED(A11)) DEALLOCATE(A11)
  ENDIF
  IF(PRESENT(A12)) THEN
    IF(ALLOCATED(A12)) DEALLOCATE(A12)
  ENDIF
