MODULE FMIN_MODULE
  INTERFACE 
    FUNCTION FMIN(AX,BX,F,TOL) RESULT(FMIN_0)
      REAL(KIND=8) :: AX
      REAL(KIND=8) :: BX
      REAL(KIND=8) :: F
      EXTERNAL F
      REAL(KIND=8) :: TOL
      REAL(KIND=8) :: FMIN_0
    END FUNCTION FMIN
  END INTERFACE 
END MODULE FMIN_MODULE
